# QQ链接解除屏蔽 (Quantumult X)
# 来源：Loon 规则转换
# 安装方式：在 QX App → rewrite_remote 中引用本文件
# 导入后会自动合并 rewrite 规则和 MITM hostname

^https:\/\/c\.pc\.qq\.com\/middlem\.html\?pfurl=(http.*)(&pfuin=.*) url 307 $1
^https:\/\/c\.pc\.qq\.com\/middlect\.html\?pfuin=.*&pfurl=(http.*)(&gjsublevel=.*) url 307 $1
^https:\/\/c\.pc\.qq\.com\/middlect\.html\?iscontinue=.*pfurl=(http.*)(&pfuin=.*) url 307 $1
^https:\/\/pingtas\.qq\.com\/webview\/pingd\?dm=c\.pc\.qq\.com&pvi=\d+&si=s\d+&url=\/middlem\.html\?pfurl%3d(http.*)(%26pfuin%3d.*%26pfuin%3d.*) url 307 $1
^https:\/\/cgi\.connect\.qq\.com\/qqconnectopen\/get_urlinfoForQQV2\?url=(http.*) url 307 $1
^https:\/\/pingtas\.qq\.com\/webview\/pingd\?dm=c\.pc\.qq\.com&pvi=\d+&si=s\d+&url=\/ios\.html\?url%3d(http.*)(%26level.*%26level.*) url 307 $1
^https:\/\/c\.pc\.qq\.com\/ios\.html\?url=(http.*)(&level=.*) url 307 $1
^https:\/\/c\.pc\.qq\.com\/index\.html\?pfurl=(http.*)(&pfuin=.*) url 307 $1

# MITM
hostname = pingtas.qq.com, c.pc.qq.com, cgi.connect.qq.com