# 雨云签到配置

[rewrite_local]
^https://api\.v2\.rainyun\.com/user/login url script-request-body https://raw.githubusercontent.com/MyUI0/pic/main/rainyun_checkin.js

[task_local]
15 7 * * * https://raw.githubusercontent.com/MyUI0/pic/main/rainyun_checkin.js, tag=雨云签到, enabled=true

[mitm]
hostname = api.v2.rainyun.com
